import { Injectable, signal } from '@angular/core';
import { Transaction } from '../models/transaction.model';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  transactions = signal<Transaction[]>([
    {
      id: 1,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2025-08-01'),
    },
    {
      id: 2,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2025-09-01'),
    },
    {
      id: 3,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2025-10-01'),
    },
    {
      id: 4,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2025-11-01'),
    },
    {
      id: 5,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2025-12-01'),
    },
    {
      id: 6,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2026-01-01'),
    },
    {
      id: 7,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2026-02-01'),
    },
    {
      id: 8,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2026-03-01'),
    },
    {
      id: 9,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2026-04-01'),
    },
    {
      id: 10,
      amount: 1500,
      type: 'income',
      category: 'other',
      date: new Date('2026-05-01'),
    },
    {
      id: 11,
      amount: 500,
      type: 'expense',
      category: 'food',
      date: new Date('2025-07-01'),
    },
    {
      id: 12,
      amount: 1500,
      type: 'expense',
      category: 'tech',
      date: new Date('2025-07-01'),
    },
    {
      id: 13,
      amount: 400,
      type: 'expense',
      category: 'food',
      date: new Date('2025-08-01'),
    },
    {
      id: 15,
      amount: 100,
      type: 'expense',
      category: 'transport',
      date: new Date('2025-08-01'),
    },
    {
      id: 15,
      amount: 150,
      type: 'expense',
      category: 'leisure',
      date: new Date('2025-08-01'),
    },
    {
      id: 16,
      amount: 600,
      type: 'expense',
      category: 'rent',
      date: new Date('2025-10-01'),
    },
    {
      id: 17,
      amount: 600,
      type: 'expense',
      category: 'rent',
      date: new Date('2025-11-01'),
    },
    {
      id: 18,
      amount: 600,
      type: 'expense',
      category: 'rent',
      date: new Date('2025-12-01'),
    },
    {
      id: 19,
      amount: 600,
      type: 'expense',
      category: 'rent',
      date: new Date('2026-01-01'),
    },
    {
      id: 20,
      amount: 650,
      type: 'expense',
      category: 'rent',
      date: new Date('2026-02-01'),
    },
    {
      id: 21,
      amount: 650,
      type: 'expense',
      category: 'rent',
      date: new Date('2026-03-01'),
    },
    {
      id: 22,
      amount: 650,
      type: 'expense',
      category: 'rent',
      date: new Date('2026-04-01'),
    },
    {
      id: 23,
      amount: 300,
      type: 'expense',
      category: 'food',
      date: new Date('2026-01-01'),
    },
    {
      id: 24,
      amount: 450,
      type: 'expense',
      category: 'food',
      date: new Date('2026-02-01'),
    },
    {
      id: 25,
      amount: 550,
      type: 'expense',
      category: 'food',
      date: new Date('2026-03-01'),
    },
    {
      id: 26,
      amount: 200,
      type: 'expense',
      category: 'food',
      date: new Date('2026-04-01'),
    },
    {
      id: 27,
      amount: 1000,
      type: 'expense',
      category: 'tech',
      date: new Date('2026-01-01'),
    },
    {
      id: 28,
      amount: 600,
      type: 'expense',
      category: 'tech',
      date: new Date('2026-04-01'),
    },
    {
      id: 29,
      amount: 300,
      type: 'expense',
      category: 'tech',
      date: new Date('2026-05-01'),
    },
    {
      id: 30,
      amount: 30,
      type: 'expense',
      category: 'transport',
      date: new Date('2026-01-01'),
    },
    {
      id: 31,
      amount: 60,
      type: 'expense',
      category: 'transport',
      date: new Date('2026-05-01'),
    },
  ]);
}
